project:
  type: book
  output-dir: docs

book:
  title: "Pesquisa de Survey"
  author: Felipe Lamarca
  chapters:
    - index.qmd
    - part: Aulas
      chapters:
        - aulas/aula-2.qmd
        - aulas/aula-3.qmd
        - aulas/aula-4.qmd
        - aulas/aula-5.qmd
    # - part: Listas
    #   chapters:
    #     - template/artigo.qmd
        
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



