---
#bibliography: master.bib
biblio-style: apsr
fontsize: 11pt
author: Felipe Lamarca
endnote: no
---

# Amostragem

## Anotações das leituras

### Groves, R. M., Fowler Jr, F. J., Couper, M. P., Lepkowski, J. M., Singer, E., & Tourangeau, R. (2011). _Survey methodology_. John Wiley & Sons. Cap. 3-4.

#### Capítulo 3 - Target Populations, Sampling Frames, and Coverage Error

> In short, statistics describing different populations can be collected in a single survey when the populations are linked to units from which measurements are taken.
>
> Among common research tools, surveys are unique in their concern about a well-specified population. For example, when conducting a randomized biomedical experiments, the researcher often pays much more attention to the experimental stimulus and the conditions of the measurement than to the identification of the population under study. The implicit assumption in such research is that the chief purpose is identifying the conditions under which the stimulus produces the hypothesized effect. The demonstration that it does so for a variety of types of subjects is secondary. **Because surveys evolved as tools to describe fixed, finite populations, survey researchers are specific and explicit about definitions of populations under study.** (p. 69)

- Target population: grupo de "elementos" sobre os quais a pesquisa de survey deseja fazer inferência usando estatísticas amostrais (_sample statistics_). A população-alvo é finita em tamanho (isto é, pode ser contada); existem durante um certo período de tempo; e são observáveis.

> For example, the target population of many U.S. household surveys is persons 18 years of age or older, "adults" who reside in housing units within the United States. (p. 70)

> There are many populations, though, for which lists of individual elements are not readily available. For example, in the United States lists are seldom avaliable in one place for all students attending school in a province or state, inmates in prisions, or even adults living in a specific county. (p. 71)

> When available sampling frames miss the target population partially or entirely, the survey researcher faces two options:
>
> 1) Redefine the target population to fit the frame better
> 
> 2) Admit the possibility of coverage error in statistics describing the original target population (p. 71)

> A common example of redefining the target population is found in telephone household surveys, where the sample is based on a frame of telephone numbers. Although the desired target population might be all adults living in the U.S. households, the attraction of using the telephone frame may persuade the researcher to alter the target population to adults living in telephone households. Alternatively, the researcher can keep the full household target population and document that approximately 2% of U.S. adults are missed because they have no telephones. (p. 71)

The match of sampling frame to target population created three potential outcomes:

- **Coverage** - when a target population element is included in the sampling frame
- **Undercoverage** - when a target population element is not included in the sampling frame
- **Ineligible (or foreign) units** - when a sampling frame element is not a target population element (e.g. business numbers in a frame of residential numbers)

Outros problemas incluem "Duplication" -- isto é, vários elementos da framing são mapeados para um único elemento da população alvo e, nesse caso, há sobrerrepresentação de alguns elementos; além disso, há também o problema de "Clustering", quando múltiplos elementos da população alvo a um único elemento da frame.

##### Undercoverage

> Undercoverage is the weakness of sampling frames promptiong the greatest fears of coverage error. It threatens to produce errors of nonobservation in survey statistics from failure to include parts of the target population in any survey using the frame. (p. 72)

> Another common concern about undercoverage in household surveys stems from the fact that sampling frames for households generally provide identification of the housing unit (through an address or telephone number) but not identifiers for persons within the household.

##### Ineligible Units

> Sometimes, sampling frames contain elements that are not part of the target population. For example, in telephone number frames, many of the numbers are nonworking or nonresidential numbers, complicating the use of the frame for the target population of households. In area probability surveys, sometimes the map materials contain units outside the target geographical area. (p. 76)

> When interviewers develop frames of household members withing a unit, they often use residence definitions that do not match the meaning of "household" held by the informant. Parents of the students living away from home often think of them as members of the household, yet many survey protocols would place them at college. The informants might tend to exclude persons unrelated to them who rent a room in the housing unit. Studies show that children in shared custody between their father and mother are likely to be duplicated by appearing in each parent's household list. (p. 76)

> Although undercoverage is a difficult problem, "ineligible" or "foreign" units in the frame can be a less difficult problem to deal with if the problem is not extensive. When foreign units are identified on the frame before selection begins, they can be purged at little cost. [...]. For example, it is known that approximately 15% of entries in residential portions of national telephone directories are numbers that are no longer in service. To achieve a sample of 100 telephone households, one could select a sample of $100(1 - 0.15) = 118$ entires from the directory, expecting that 18 are going to be out-of-service numbers. (p. 76)

##### Clustering

> A telephone directory lists telephone households in order by surname, given name, and address. When sampling adults from this frame, an immediately obvious problem is the clustering of eligible persons that occurs. "Clusterng" means that multiple elements of the target population are represented by the same frame element. A telephone listing in the directory may have a single or two or more adults living there. (p. 77)

> One way to react to clustering of target population elements is by simply selecting all eligible units in the selected telephone households (or all eligible units in a cluster). With this design, the probability of selection of the cluster applies to all elements in the cluster. (p. 77)

> After sample selection, there is one other issue that needs to be addressed in this form of cluster sampling: unequal probabilities of selection. If all frame elements are given equal chances, but one eligible selection is made from each, then elements in large clusters have lower overall probabilities of selection than elements in small clusters. For example, an eligible person chosen in a telephone household containing two eligibles has a chance of one-half of being selected, given that the household was sampled, whereas those in a household with four eligibles have a one-in-four chance. (p. 78)

##### Duplication

> "Duplication" means that a single target population element is associated with multiple frame elements. In the telephone survey example, this may arise when a single telephone household has more than one listing in a telephone directory. (p. 79)

> The problem that arises with this kind of frame problem is similar to that encountered with clustering. Target population elements with multiple frame units have higher chances of selection and will be overrepresented in the sample, relative to the population. If there is a correlation between duplication and variables of interest, survey estimates will be biased. In survey estimation, the problem is that both the presence of duplication and the correlation between duplication and survey variables are often unknown. (p. 79)

##### Clustering and Duplication

> It is also possible to have frame units mapped to multiple population elements. For example, in telephone household surveys of adults, one may encounter a household with several adults who have multiple entries in the directory. (p. 80)

##### Desenhos de amostragem e seus problemas

Há vários framing problems relacionados a pesquisas de survey. Há uma série de desenhos alternativos, que também possuem problemas atrelados:

- **Area frames (list of area units like census tracts or counties)**: primeiro, um subconjunto de áreas é selecionado; depois, listagens de endereços são geradas para a área selecionada. 

- **Telephone number frames for households and persons**: ao usar linhas fixas, falhamos em cobrir cerca de 20% das unidades residenciais dos Estados Unidos. Além disso, um percentual menor possui mais de uma linha fixa e acabam sendo duplicados. Além disso, com o uso de celulares, essa abordagem torna-se mais complicada -- mesmo porque números de telefone celular são associados a uma pessoa, e não a um endereço.

- **Frames for Web Surveys of General Populations**: "The e-mail frame, however, fails to cover large portions of the household population. It has duplication problems because one person can have many different e-mail addresses, and it has clustering problems because more than one person can share an e-mail address." (p. 83). 

"In short, without a universal frame of e-mail addresses with known links to individual population elements, some survey practices have begun to ignore the frame development step. Without a well-defined sampling frame, the coverage error of resulting estimates is completely unknowable." (p. 84).

##### Coverage error

> Undercoverage is a difficult problem, and may be an important source of coverage error in surveys. It is important to note, though, that coverage error is a property of sample statistics and estimates made from surveys. 

No caso de uma estimativa de média, o viés de cobertura é dado por:

$$
\bar{Y}_C - \bar{Y} = \dfrac{U}{N} (\bar{Y}_C - \bar{Y}_U),
$$

one $\bar{Y}$ é a média da população total, $\bar{Y}_C$ é a média da população coberta e $\bar{Y}_U$ é a média da população não coberta. $U$ é o número de unidades não cobertas e $N$ é o número total de unidades. "**Thus, the error due to not covering the $N-C$ units left out of the frame is a function of the proportion 'not covered' and the difference between means for the covered and the not covered.**" (p. 88).

##### Reduzindo o erro de cobertura

- **The Half-Open Interval:** "Consider, for example, address or housing unit lists used in household surveys. These lists may become out of date and miss units quickly. They may also have missed housing units that upon closer inspection could be added to the list. Since address lists are typically in a particular geographic order, it is possible to add units to the frame only for selected frame elements, rather than updating the entire list." (p. 88).

- **Multiplicy sampling**: "Some frame supplementation methods add elements to a population through network sampling." (p. 90).

- **Multiple frame designs**: "For example, an out-of-date set of listings of housing units can be supplemented by a frame of newly constructed housing units obtained from planning departments in governmental units responsible for zoning where sample addressses are located" (p. 91). 

"At times, the supplemental frame may cover a completely separate portion of the population. In most cases, though, supplemental frames overlap with the principal frame. In such cases, multiple framing sampling and estimation procedures are employed to correct for unequal probabilities of selection and possibly to yield improved precision for survey estimates." (p. 91).

"There are several solutions to the overlap and overrepresentation problem. One is to screen the area household frame. At the doorstep, before an interview is conducted, the interviewer determines whether the household has a fixed-line telephone that would allow it to be reached by telephone. If so, the unit is not selected and no interview is attempted. With this procedure, the overlap is eliminated, and the dual frame sample design has complete coverage of households.

A second solution is to attempt interviews at all sample households in both frames, but to determine the chance of selection for each household. Households from the nonoverlap portion of the sample, the nontelephone households can be selected from the area frame and, thus, have one chance of selection. Telephone households have two chances, one from the telephone frame and the other from the area household frame. Thus, theis chance of selection is $p_{RDD} + p_{area} - p_{RDD} \times p_{area}$, where $p_{RDD}$ and $p_{area}$ denote the chances of selection for the RDD and area sample households. A compensatory weight can be computed as the inverse of the probability of selection: $1/p_{area}$ for nontelephone households and $1/(p_{RDD} + p_{area} - p_{RDD} \times p_{area})$ for telephone households, regardless of which frame was used.

A third solution was proposed by Hartley (1962) and others. They suggested that the overlap of the frames be used to obtain a more efficient estimator. [...]. The telephone and nontelephone domains are combined using a weight that is the proportion of the telefone households in the target population, say $W_{tel}$. The dual frame estimator for this particular example is:

$$
\bar{y} = (1 - W_{tel}) p_{non-tel} + W_{tel} [ \theta p_{RDD-tel} + (1 - \theta) p_{area-tel}],
$$

where $\theta$ is the mixing parameter chosen to maximize precision." (p. 92).
